[workspace]
default-members=["example-app"]
members = [
    "example-app",
    "example-impl",
    "hot-reload",
    "hot-reloaded-state",
    # For debugging
    "raw_sync-rs",
    "shared_memory-rs",
]
